### ISSUE TITLE
跟着教程一步步做的还是连不通

### ISSUE THREAD

**Issue by quan9364** [yonggekkk/CF-cdn-domain#1]
勇哥，worker与域名关联上了，在代理模式下浏览器打开自己的域名/uuid也是可以打开配置界面。但问题是在v2rayN里把配置填上去后，测速显示 503错误，搞了一个下午还是没搞出来，请问是什么原因呀？我在“伪装域名“里已经填了我的CF小黄云的域名，”地址“这一栏我填的是icook.hk。谢谢

**Comment by quan9364** [comment]
问题找到了，是v2ray版本太低，安装新版本就好了

**Comment by yonggekkk** [comment]
好吧
